name: Shell Commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -vs
          npm -v
      - name: python command
        run: |
          import os
          print(os.environ["PATH"])
        shell: python
  run-windows-command:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
